### ISSUE TITLE
Issue 1

### ISSUE THREAD

**Issue by DougyUK** [bnoordhuis/bspc#1]
ryan-douglass-power-mac-g4:~ Dougy$ cd /Users/Dougy/Desktop/logic\ 8\ jam\ packs/bnoordhuis-bspc-a7bf834/
ryan-douglass-power-mac-g4:bnoordhuis-bspc-a7bf834 Dougy$ make
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o _files.o -c _files.c
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o aas_areamerging.o -c aas_areamerging.c
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o aas_cfg.o -c aas_cfg.c
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o aas_create.o -c aas_create.c
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o aas_edgemelting.o -c aas_edgemelting.c
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o aas_facemerging.o -c aas_facemerging.c
aas_facemerging.c: In function ‘AAS_CanMergePlaneFaces’:
aas_facemerging.c:220: warning: ‘faceflags’ may be used uninitialized in this function
aas_facemerging.c: In function ‘AAS_MergeAreaPlaneFaces’:
aas_facemerging.c:220: warning: ‘faceflags’ may be used uninitialized in this function
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o aas_file.o -c aas_file.c
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o aas_gsubdiv.o -c aas_gsubdiv.c
aas_gsubdiv.c: In function ‘AAS_LadderSubdivideArea_r’:
aas_gsubdiv.c:531: warning: ‘lowestpoint[0]’ may be used uninitialized in this function
aas_gsubdiv.c:531: warning: ‘lowestpoint[1]’ may be used uninitialized in this function
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o aas_map.o -c aas_map.c
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o aas_prunenodes.o -c aas_prunenodes.c
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o aas_store.o -c aas_store.c
aas_store.c: In function ‘AAS_StoreArea’:
aas_store.c:911: warning: ‘w’ may be used uninitialized in this function
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o be_aas_bspc.o -c be_aas_bspc.c
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o deps/botlib/be_aas_bspq3.o -c deps/botlib/be_aas_bspq3.c
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o deps/botlib/be_aas_cluster.o -c deps/botlib/be_aas_cluster.c
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o deps/botlib/be_aas_move.o -c deps/botlib/be_aas_move.c
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o deps/botlib/be_aas_optimize.o -c deps/botlib/be_aas_optimize.c
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o deps/botlib/be_aas_reach.o -c deps/botlib/be_aas_reach.c
deps/botlib/be_aas_reach.c: In function ‘AAS_Reachability_Ladder’:
deps/botlib/be_aas_reach.c:2388: warning: ‘lowestpoint[0]’ may be used uninitialized in this function
deps/botlib/be_aas_reach.c:2388: warning: ‘lowestpoint[1]’ may be used uninitialized in this function
deps/botlib/be_aas_reach.c: In function ‘AAS_Reachability_Step_Barrier_WaterJump_WalkOffLedge’:
deps/botlib/be_aas_reach.c:1071: warning: ‘water_bestend[0]’ may be used uninitialized in this function
deps/botlib/be_aas_reach.c:1071: warning: ‘water_bestend[1]’ may be used uninitialized in this function
deps/botlib/be_aas_reach.c:1071: warning: ‘water_bestend[2]’ may be used uninitialized in this function
deps/botlib/be_aas_reach.c:1071: warning: ‘water_bestnormal[0]’ may be used uninitialized in this function
deps/botlib/be_aas_reach.c:1071: warning: ‘water_bestnormal[1]’ may be used uninitialized in this function
deps/botlib/be_aas_reach.c:1071: warning: ‘water_bestnormal[2]’ may be used uninitialized in this function
deps/botlib/be_aas_reach.c:1071: warning: ‘water_beststart[0]’ may be used uninitialized in this function
deps/botlib/be_aas_reach.c:1071: warning: ‘water_beststart[1]’ may be used uninitialized in this function
deps/botlib/be_aas_reach.c:1071: warning: ‘water_beststart[2]’ may be used uninitialized in this function
deps/botlib/be_aas_reach.c:1070: warning: ‘ground_bestend[0]’ may be used uninitialized in this function
deps/botlib/be_aas_reach.c:1070: warning: ‘ground_bestend[1]’ may be used uninitialized in this function
deps/botlib/be_aas_reach.c:1070: warning: ‘ground_bestend[2]’ may be used uninitialized in this function
deps/botlib/be_aas_reach.c:1070: warning: ‘ground_bestnormal[0]’ may be used uninitialized in this function
deps/botlib/be_aas_reach.c:1070: warning: ‘ground_bestnormal[1]’ may be used uninitialized in this function
deps/botlib/be_aas_reach.c:1070: warning: ‘ground_bestnormal[2]’ may be used uninitialized in this function
deps/botlib/be_aas_reach.c:1070: warning: ‘ground_beststart[0]’ may be used uninitialized in this function
deps/botlib/be_aas_reach.c:1070: warning: ‘ground_beststart[1]’ may be used uninitialized in this function
deps/botlib/be_aas_reach.c:1070: warning: ‘ground_beststart[2]’ may be used uninitialized in this function
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o deps/botlib/be_aas_sample.o -c deps/botlib/be_aas_sample.c
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o brushbsp.o -c brushbsp.c
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o bspc.o -c bspc.c
bspc.c: In function ‘main’:
bspc.c:852: warning: implicit declaration of function ‘AAS_InitBotImport’
bspc.c:853: warning: implicit declaration of function ‘AAS_InitClustering’
bspc.c:923: warning: implicit declaration of function ‘AAS_ShowTotals’
bspc.c:508: warning: ‘qfiles’ may be used uninitialized in this function
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o deps/qcommon/cm_load.o -c deps/qcommon/cm_load.c
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o deps/qcommon/cm_patch.o -c deps/qcommon/cm_patch.c
deps/qcommon/cm_patch.c: In function ‘CM_TraceThroughPatchCollide’:
deps/qcommon/cm_patch.c:1382: warning: ‘bestplane[0]’ may be used uninitialized in this function
deps/qcommon/cm_patch.c:1382: warning: ‘bestplane[1]’ may be used uninitialized in this function
deps/qcommon/cm_patch.c:1382: warning: ‘bestplane[2]’ may be used uninitialized in this function
deps/qcommon/cm_patch.c:1382: warning: ‘bestplane[3]’ may be used uninitialized in this function
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o deps/qcommon/cm_test.o -c deps/qcommon/cm_test.c
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o deps/qcommon/cm_trace.o -c deps/qcommon/cm_trace.c
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o csg.o -c csg.c
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o glfile.o -c glfile.c
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o l_bsp_ent.o -c l_bsp_ent.c
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o l_bsp_hl.o -c l_bsp_hl.c
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o l_bsp_q1.o -c l_bsp_q1.c
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o l_bsp_q2.o -c l_bsp_q2.c
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o l_bsp_q3.o -c l_bsp_q3.c
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o l_bsp_sin.o -c l_bsp_sin.c
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o l_cmd.o -c l_cmd.c
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o deps/botlib/l_libvar.o -c deps/botlib/l_libvar.c
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o l_log.o -c l_log.c
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o l_math.o -c l_math.c
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o l_mem.o -c l_mem.c
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o l_poly.o -c l_poly.c
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o deps/botlib/l_precomp.o -c deps/botlib/l_precomp.c
deps/botlib/l_precomp.c: In function ‘PC_ExpandBuiltinDefine’:
deps/botlib/l_precomp.c:739: warning: pointer targets in passing argument 1 of ‘ctime’ differ in signedness
deps/botlib/l_precomp.c:754: warning: pointer targets in passing argument 1 of ‘ctime’ differ in signedness
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o l_qfiles.o -c l_qfiles.c
l_qfiles.c: In function ‘FindQuakeFilesWithPakFilter’:
l_qfiles.c:421: warning: unused variable ‘done’
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o deps/botlib/l_script.o -c deps/botlib/l_script.c
deps/botlib/l_script.c: In function ‘PS_ReadNumber’:
deps/botlib/l_script.c:726: warning: passing argument 4 of ‘NumberValue’ from incompatible pointer type
deps/botlib/l_script.c: In function ‘LoadScriptFile’:
deps/botlib/l_script.c:1368: warning: implicit declaration of function ‘COM_Compress’
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o deps/botlib/l_struct.o -c deps/botlib/l_struct.c
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o l_threads.o -c l_threads.c
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o l_utils.o -c l_utils.c
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o leakfile.o -c leakfile.c
leakfile.c: In function ‘LeakFile’:
leakfile.c:72: warning: ‘nextnode’ may be used uninitialized in this function
leakfile.c:71: warning: ‘nextportal’ may be used uninitialized in this function
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o map.o -c map.c
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o map_hl.o -c map_hl.c
map_hl.c: In function ‘HL_MergeBrushes’:
map_hl.c:509: warning: ‘nummerges’ may be used uninitialized in this function
map_hl.c: In function ‘HL_TextureBrushes’:
map_hl.c:704: warning: ‘numbrushes’ may be used uninitialized in this function
map_hl.c: In function ‘HL_CreateMapBrushes’:
map_hl.c:1025: warning: ‘i’ may be used uninitialized in this function
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o map_q1.o -c map_q1.c
map_q1.c: In function ‘Q1_MergeBrushes’:
map_q1.c:565: warning: ‘nummerges’ may be used uninitialized in this function
map_q1.c: In function ‘Q1_TextureBrushes’:
map_q1.c:760: warning: ‘numbrushes’ may be used uninitialized in this function
map_q1.c: In function ‘Q1_CreateMapBrushes’:
map_q1.c:1083: warning: ‘i’ may be used uninitialized in this function
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o map_q2.o -c map_q2.c
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o map_q3.o -c map_q3.c
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o map_sin.o -c map_sin.c
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o deps/qcommon/md4.o -c deps/qcommon/md4.c
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o nodraw.o -c nodraw.c
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o portals.o -c portals.c
portals.c: In function ‘MakeNodePortal’:
portals.c:411: warning: ‘dist’ may be used uninitialized in this function
portals.c:412: warning: ‘side’ may be used uninitialized in this function
portals.c: In function ‘SplitNodePortals’:
portals.c:485: warning: ‘side’ may be used uninitialized in this function
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o textures.o -c textures.c
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o tree.o -c tree.c
gcc -Dstricmp=strcasecmp -DCom_Memcpy=memcpy -DCom_Memset=memset -DMAC_STATIC= -DQDECL= -DLINUX -DBSPC -D_FORTIFY_SOURCE=2 -I. -Ideps -Wall -O3 -ffast-math -o deps/qcommon/unzip.o -c deps/qcommon/unzip.c
deps/qcommon/unzip.c: In function ‘huft_build’:
deps/qcommon/unzip.c:3037: warning: ‘r.base’ may be used uninitialized in this function
gcc -lm -lpthread -o bspc _files.o aas_areamerging.o aas_cfg.o aas_create.o aas_edgemelting.o aas_facemerging.o aas_file.o aas_gsubdiv.o aas_map.o aas_prunenodes.o aas_store.o be_aas_bspc.o deps/botlib/be_aas_bspq3.o deps/botlib/be_aas_cluster.o deps/botlib/be_aas_move.o deps/botlib/be_aas_optimize.o deps/botlib/be_aas_reach.o deps/botlib/be_aas_sample.o brushbsp.o bspc.o deps/qcommon/cm_load.o deps/qcommon/cm_patch.o deps/qcommon/cm_test.o deps/qcommon/cm_trace.o csg.o glfile.o l_bsp_ent.o l_bsp_hl.o l_bsp_q1.o l_bsp_q2.o l_bsp_q3.o l_bsp_sin.o l_cmd.o deps/botlib/l_libvar.o l_log.o l_math.o l_mem.o l_poly.o deps/botlib/l_precomp.o l_qfiles.o deps/botlib/l_script.o deps/botlib/l_struct.o l_threads.o l_utils.o leakfile.o map.o map_hl.o map_q1.o map_q2.o map_q3.o map_sin.o deps/qcommon/md4.o nodraw.o portals.o textures.o tree.o deps/qcommon/unzip.o
Undefined symbols:
  "_LongSwap", referenced from:
      _CMod_LoadSubmodels in cm_load.o
      _CMod_LoadSubmodels in cm_load.o
      _CMod_LoadSubmodels in cm_load.o
      _CMod_LoadSubmodels in cm_load.o
      _CMod_LoadNodes in cm_load.o
      _CMod_LoadNodes in cm_load.o
      _CMod_LoadLeafs in cm_load.o
      _CMod_LoadLeafs in cm_load.o
      _CMod_LoadLeafs in cm_load.o
      _CMod_LoadLeafs in cm_load.o
      _CMod_LoadLeafs in cm_load.o
      _CMod_LoadLeafs in cm_load.o
      _CMod_LoadLeafBrushes in cm_load.o
      _CMod_LoadLeafSurfaces in cm_load.o
      _CMod_LoadBrushSides in cm_load.o
      _CMod_LoadBrushSides in cm_load.o
      _CMod_LoadPatches in cm_load.o
      _CMod_LoadPatches in cm_load.o
      _CMod_LoadPatches in cm_load.o
      _CMod_LoadPatches in cm_load.o
      _CMod_LoadPatches in cm_load.o
      _CM_LumpChecksum in cm_load.o
      _CMod_LoadBrushes in cm_load.o
      _CMod_LoadBrushes in cm_load.o
      _CMod_LoadBrushes in cm_load.o
      _CMod_LoadShaders in cm_load.o
      _CMod_LoadShaders in cm_load.o
      _CMod_LoadVisibility in cm_load.o
      _CMod_LoadVisibility in cm_load.o
      _CM_LoadMap in cm_load.o
      _CM_LoadMap in cm_load.o
      _CM_LoadMap in cm_load.o
      _CM_LoadMap in cm_load.o
      _CM_Checksum in cm_load.o
      _CM_Checksum in cm_load.o
      _CM_Checksum in cm_load.o
      _CM_Checksum in cm_load.o
      _CM_Checksum in cm_load.o
      _CM_Checksum in cm_load.o
      _CM_Checksum in cm_load.o
      _CM_Checksum in cm_load.o
      _CM_Checksum in cm_load.o
      _CM_Checksum in cm_load.o
      _CM_Checksum in cm_load.o
      _CM_Checksum in cm_load.o
      _unzOpen in unzip.o
      _unzOpen in unzip.o
      _unzOpen in unzip.o
      _unzlocal_GetCurrentFileInfoInternal in unzip.o
      _unzlocal_GetCurrentFileInfoInternal in unzip.o
      _unzlocal_GetCurrentFileInfoInternal in unzip.o
      _unzlocal_GetCurrentFileInfoInternal in unzip.o
      _unzlocal_GetCurrentFileInfoInternal in unzip.o
      _unzlocal_GetCurrentFileInfoInternal in unzip.o
      _unzlocal_GetCurrentFileInfoInternal in unzip.o
      _unzOpenCurrentFile in unzip.o
      _unzOpenCurrentFile in unzip.o
      _unzOpenCurrentFile in unzip.o
      _unzOpenCurrentFile in unzip.o
      _unzOpenCurrentFile in unzip.o
  "_FloatSwap", referenced from:
      _CMod_LoadSubmodels in cm_load.o
      _CMod_LoadSubmodels in cm_load.o
      _CMod_LoadPlanes in cm_load.o
      _CMod_LoadPlanes in cm_load.o
      _CMod_LoadPatches in cm_load.o
      _CMod_LoadPatches in cm_load.o
      _CMod_LoadPatches in cm_load.o
  "_ShortSwap", referenced from:
      _unzOpen in unzip.o
      _unzOpen in unzip.o
      _unzOpen in unzip.o
      _unzOpen in unzip.o
      _unzOpen in unzip.o
      _unzlocal_GetCurrentFileInfoInternal in unzip.o
      _unzlocal_GetCurrentFileInfoInternal in unzip.o
      _unzlocal_GetCurrentFileInfoInternal in unzip.o
      _unzlocal_GetCurrentFileInfoInternal in unzip.o
      _unzlocal_GetCurrentFileInfoInternal in unzip.o
      _unzlocal_GetCurrentFileInfoInternal in unzip.o
      _unzlocal_GetCurrentFileInfoInternal in unzip.o
      _unzlocal_GetCurrentFileInfoInternal in unzip.o
      _unzlocal_GetCurrentFileInfoInternal in unzip.o
      _unzOpenCurrentFile in unzip.o
      _unzOpenCurrentFile in unzip.o
      _unzOpenCurrentFile in unzip.o
      _unzOpenCurrentFile in unzip.o
      _unzOpenCurrentFile in unzip.o
ld: symbol(s) not found
collect2: ld returned 1 exit status
make: **\* [bspc] Error 1
ryan-douglass-power-mac-g4:bnoordhuis-bspc-a7bf834 Dougy$ ./bspc
-bash: ./bspc: No such file or directory

**Comment by bnoordhuis** [comment]
Thanks for the report, it should be fixed in 3d73121.
